import { Pool } from "pg";
import { afterAll, beforeAll, beforeEach, describe, expect, it } from "vitest";

import { SensorConflictError } from "@/modules/sensors/errors/sensor-conflict.error.js";
import { PgSensorRepository } from "@/modules/sensors/repositories/sensor.repository.js";

// Testes de integração do repositório Postgres. Rodam só quando
// TEST_DATABASE_URL aponta para um Postgres descartável (o CI sobe um).
// Tudo acontece num schema próprio, apagado no fim: nunca toca tabelas reais.
const TEST_DATABASE_URL = process.env.TEST_DATABASE_URL;
const SCHEMA = `it_sensors_${process.pid}`;

describe.skipIf(!TEST_DATABASE_URL)(
  "PgSensorRepository (Postgres real)",
  () => {
    let pool: Pool;
    let repository: PgSensorRepository;

    const sensor = (identifier: string, stationId = 1) => ({
      station_id: stationId,
      sensor_type_id: 1,
      local_identifier: identifier,
      operational_status: true,
    });

    beforeAll(async () => {
      const admin = new Pool({ connectionString: TEST_DATABASE_URL });
      await admin.query(`DROP SCHEMA IF EXISTS ${SCHEMA} CASCADE`);
      await admin.query(`CREATE SCHEMA ${SCHEMA}`);
      await admin.query(`
      CREATE TABLE ${SCHEMA}.stations (id integer PRIMARY KEY);
      CREATE TABLE ${SCHEMA}.sensor_types (id integer PRIMARY KEY);
      INSERT INTO ${SCHEMA}.stations (id) VALUES (1), (2);
      INSERT INTO ${SCHEMA}.sensor_types (id) VALUES (1);
      CREATE TABLE ${SCHEMA}.sensors (
        id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        station_id integer NOT NULL REFERENCES ${SCHEMA}.stations (id),
        sensor_type_id integer NOT NULL REFERENCES ${SCHEMA}.sensor_types (id),
        local_identifier varchar(50) NOT NULL,
        operational_status boolean NOT NULL DEFAULT true,
        created_at timestamp NOT NULL DEFAULT current_timestamp,
        CONSTRAINT sensors_station_identifier_unique UNIQUE (station_id, local_identifier)
      );
      CREATE TABLE ${SCHEMA}.alert_configs (
        id integer PRIMARY KEY,
        sensor_id integer NOT NULL REFERENCES ${SCHEMA}.sensors (id)
      );
    `);
      await admin.end();

      pool = new Pool({
        connectionString: TEST_DATABASE_URL,
        options: `-c search_path=${SCHEMA}`,
      });
      repository = new PgSensorRepository(pool);
    });

    beforeEach(async () => {
      await pool.query("TRUNCATE alert_configs, sensors RESTART IDENTITY");
    });

    afterAll(async () => {
      await pool?.query(`DROP SCHEMA IF EXISTS ${SCHEMA} CASCADE`);
      await pool?.end();
    });

    it("cria, busca, atualiza e exclui gravando no banco", async () => {
      const created = await repository.create(sensor("TEMP_01"));
      expect(created).toMatchObject({ id: 1, local_identifier: "TEMP_01" });
      expect(created.created_at).toMatch(/Z$/);

      expect(await repository.findById(1)).toEqual(created);
      expect(await repository.findByStationAndIdentifier(1, "temp_01")).toEqual(
        created,
      );

      const updated = await repository.update(1, {
        local_identifier: "TEMP_02",
        operational_status: false,
      });
      expect(updated).toMatchObject({
        station_id: 1,
        local_identifier: "TEMP_02",
        operational_status: false,
      });
      expect(await repository.update(99, { station_id: 1 })).toBeNull();

      expect(await repository.delete(1)).toBe(true);
      expect(await repository.delete(1)).toBe(false);
      expect(await repository.findById(1)).toBeNull();
    });

    it("pagina e filtra por estação", async () => {
      await repository.create(sensor("A", 1));
      await repository.create(sensor("B", 1));
      await repository.create(sensor("C", 2));

      const page = await repository.findPaginated({ page: 2, limit: 2 });
      expect(page.data.map((s) => s.local_identifier)).toEqual(["C"]);
      expect(page.meta).toEqual({
        total_records: 3,
        total_pages: 2,
        current_page: 2,
      });

      const station1 = await repository.findPaginated({ station_id: 1 });
      expect(station1.meta.total_records).toBe(2);
      expect(await repository.countBySensorTypeId(1)).toBe(3);
    });

    it("confere estação e tipo de sensor", async () => {
      expect(await repository.stationExists(1)).toBe(true);
      expect(await repository.stationExists(9)).toBe(false);
      expect(await repository.sensorTypeExists(1)).toBe(true);
      expect(await repository.sensorTypeExists(9)).toBe(false);
    });

    it("converte violações do banco em 409", async () => {
      await repository.create(sensor("DUP"));
      await expect(repository.create(sensor("DUP"))).rejects.toBeInstanceOf(
        SensorConflictError,
      );
      await expect(repository.create(sensor("X", 9))).rejects.toBeInstanceOf(
        SensorConflictError,
      );

      const outro = await repository.create(sensor("OUTRO"));
      await expect(
        repository.update(outro.id, { local_identifier: "DUP" }),
      ).rejects.toBeInstanceOf(SensorConflictError);

      await pool.query(
        "INSERT INTO alert_configs (id, sensor_id) VALUES (1, 1)",
      );
      await expect(repository.delete(1)).rejects.toBeInstanceOf(
        SensorConflictError,
      );
    });
  },
);
